# Generated by Django 2.0.7 on 2018-09-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='interests',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
