# Generated by Django 2.0.7 on 2018-09-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180909_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
