# Generated by Django 2.0.7 on 2018-09-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180910_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='phone',
            field=models.BigIntegerField(blank=True),
        ),
    ]
